Test IDs added and working for Create Account Flow
EdgeApp/edge-login-ui pull request #278
Opened 2021-04-19 21:14 UTC by M4RcB4

2021-04-19 22:59 UTC, swansontec requested changes
Found some Flow issues.

2021-04-19 22:59 UTC, swansontec commented on packages/edge-login-ui-rn/src/components/abSpecific/AccountInfoComponent.js
> +          testID={this.props.testID}
This was not added to the props above. Flow should have caught this in the pre-commit hook.

2021-04-19 22:59 UTC, swansontec commented on packages/edge-login-ui-rn/src/components/common/Checkbox.js
> +  testID?: String,
Lowercase `string`, also caught by Flow.

2021-04-19 22:59 UTC, swansontec commented on packages/edge-login-ui-rn/src/components/common/MaterialInput.js
> +        testID={this.props.testID}
Error. You will need to add `testID` to the file `flow-typed/react-native-material-textfield.js`

2021-04-20 19:59 UTC, M4RcB4 commented
@swansontec I squashed the commits. Should be ready for approval/merge. Do we wait for re-review, or do you usually merge it if the changes requested were added?

2021-04-20 20:36 UTC, swansontec approved these changes

2021-04-20 20:38 UTC, merged