UI2 create account set up pin
EdgeApp/edge-login-ui pull request #305
Opened 2021-06-16 15:55 UTC by dbo1dyrev

PR Requirements
If you have made any visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS Tablet
- [x] Tested on small Android
- [ ] n/a
<img width="436" alt="Screenshot 2021-06-16 at 18 52 34" src="https://user-images.githubusercontent.com/68349436/122252486-107dca80-ced4-11eb-8494-7240db307cc9.png">
<img width="437" alt="Screenshot 2021-06-16 at 18 52 44" src="https://user-images.githubusercontent.com/68349436/122252526-183d6f00-ced4-11eb-81f4-9cff698d692f.png">
<img width="436" alt="Screenshot 2021-06-16 at 18 52 54" src="https://user-images.githubusercontent.com/68349436/122252560-1d022300-ced4-11eb-9d29-305a2856e215.png">

2021-06-16 20:12 UTC, paullinator commented
Remove the red warning box that the pin must be four digits. This was supposed to be removed from the design.

2021-06-16 20:12 UTC, paullinator requested changes
See comment. This is not a thorough review but I at least want that UI change

2021-06-17 14:16 UTC, dbo1dyrev commented
<img width="438" alt="Screenshot 2021-06-17 at 17 15 13" src="https://user-images.githubusercontent.com/68349436/122414217-a4609c80-cf8f-11eb-8616-907a9b309f0e.png">

>Remove the red warning box that the pin must be four digits. This was supposed to be removed from the design.

fixed it

2021-06-25 03:11 UTC, thehobbit85 requested changes
See comments

2021-06-25 03:11 UTC, thehobbit85 commented on packages/edge-login-ui-rn/src/components/themed/FourDigitInput.js
> +            <View style={styles.dotContainer}>
You should try and avoid writing code like this.
When you have a repeating pattern, you should generalize it like here: 

https://github.com/EdgeApp/edge-react-gui/blob/develop/src/components/themed/PinDots.js

And in this case you should also separate the "PinDots" component like the one in the link.

2021-06-25 03:11 UTC, thehobbit85 commented on packages/edge-login-ui-rn/src/components/themed/FourDigitInput.js
> +// @flow
The word "Four" shouldn't be a part of any file/folder/component name.
We might change it tomorrow to 5, or 6, or whatever. It should be kept general and the length of the Pin Code should be a prop.

2021-06-25 03:11 UTC, thehobbit85 commented on packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPinScreen.js
> +              pin.length === 4 && !pinErrorMessage && !createErrorMessage
Avoid using numbers directly in the code.
Always pass them as a Param/Constant.

2021-06-25 13:47 UTC, dbo1dyrev commented
add new commit "Add Pin Dots component"
rebase "Change the PIN input design to match the new design"

2021-07-01 10:14 UTC, dbo1dyrev commented
<img width="434" alt="Screenshot 2021-07-01 at 13 02 17" src="https://user-images.githubusercontent.com/68349436/124106759-33c87e00-da6d-11eb-97fa-8f05dec87da4.png">

2021-07-02 10:55 UTC, thehobbit85 requested changes
Magic number again

2021-07-02 10:55 UTC, thehobbit85 commented on packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPinScreen.js
> +    if (pin.length !== 4 || pinErrorMessage) {
Another magic number

2021-07-02 11:29 UTC, thehobbit85 commented
/rebase-autosquash

2021-07-02 11:30 UTC, dbo1dyrev commented
> /rebase-autosquash

already did it

2021-07-02 11:32 UTC, merged