UI2 Account Confirmation terms screen
EdgeApp/edge-login-ui pull request #308
Opened 2021-06-20 19:48 UTC by dbo1dyrev

PR Requirements
If you have made any visual changes to the GUI. Make sure you have:

- [ ] Tested on iOS Tablet
- [ ]  Tested on small Android
- [ ]  n/a

<img width="432" alt="Screenshot 2021-06-20 at 22 38 48" src="https://user-images.githubusercontent.com/68349436/122686435-a3db3680-d219-11eb-8b24-a0cc789ef274.png">
<img width="435" alt="Screenshot 2021-06-20 at 22 38 58" src="https://user-images.githubusercontent.com/68349436/122686441-a63d9080-d219-11eb-85b5-3bf341c1e951.png">

2021-06-25 03:32 UTC, thehobbit85 approved these changes

2021-06-30 09:46 UTC, thehobbit85 requested changes
Fix button styling

2021-07-01 11:13 UTC, dbo1dyrev commented
<img width="433" alt="Screenshot 2021-07-01 at 13 48 49" src="https://user-images.githubusercontent.com/68349436/124115472-82c6e100-da76-11eb-8b5b-d035f2084c81.png">

2021-07-02 11:02 UTC, thehobbit85 approved these changes

2021-07-02 11:42 UTC, merged