Add recovery translations
EdgeApp/edge-login-ui pull request #319
Opened 2021-07-14 09:39 UTC by axenov-it

2021-07-14 09:44 UTC, axenov-it commented
This functionality add translations for recovery password of list, for recovery questions

![image](https://user-images.githubusercontent.com/67971974/125600565-c688bd9f-fbdd-4be9-afe3-5d62eb45cac9.png)

2021-07-15 22:39 UTC, swansontec requested changes
Yes, this is exactly what we wanted to do. We don't actually use the hints (`category` & `min_length`), but maybe we should, so I do approve of keeping that information in place.

2021-07-15 22:39 UTC, swansontec commented on packages/edge-login-ui-rn/src/common/locales/en_US.js
> +  change_recovery_same_question1:
Please change all of these names to `change_recovery_question1` and so forth, without the word "same" in there.

2021-07-17 02:24 UTC, thehobbit85 approved these changes

2021-07-17 02:25 UTC, merged