William/rn readme
EdgeApp/edge-login-ui pull request #364
Opened 2022-01-17 19:04 UTC by swansontec

2022-01-20 23:16 UTC, paullinator requested changes

2022-01-20 23:16 UTC, paullinator commented on packages/edge-login-ui-rn/README.md
> +`npm install --save edge-core-js edge-login-ui-rn`
should this be `yarn`?

2022-01-21 02:12 UTC, swansontec commented on packages/edge-login-ui-rn/README.md
> +`npm install --save edge-core-js edge-login-ui-rn`
Good call

2022-01-27 18:20 UTC, paullinator approved these changes

2022-01-28 00:38 UTC, swansontec commented
/rebase-autosquash

2022-01-28 00:39 UTC, merged